name: GitHub Actions Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  schedule:
    - cron: 15 */6 * * *
  workflow_dispatch:
    inputs:
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: true
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: '20'
      - run: echo "Branch name is:" ${GITHUB_REF_NAME}
      - run: echo "event type is:" ${{GITHUB_HEAD_REF}} 
